export { default as HomePage } from './HomePage.jsx'
export { default as AboutPage } from './AboutPage.jsx'
export { default as SkillsPage } from './SkillsPage.jsx'
export { default as ProjectsPage } from './ProjectsPage.jsx'
export { default as ExperiencePage } from './ExperiencePage.jsx'
export { default as ContactPage } from './ContactPage.jsx'
export { default as NotFoundPage } from './NotFoundPage.jsx'
